In [2]:
# ! pip install tensorflow --upgrade

**TensorFlow** is a free and open-source software library for machine learning.

**Keras** is a deep learning API written in Python, running on top of the machine learning platform TensorFlow.

## History between Keras and TensorFlow:

- Keras was first developed by Francois Chollet for his own reserach in March 27th, 2015. Back then, TensorFlow hasn't been developed. There weren't too many deep learning libraries available - the popular ones included Torch, Theano, and Caffe. 
- In order to train the neural networks, Keras required a **backend** (computational engine). Keras's default backend was Theano until v1.1.0. At the same time, Google released TensorFlow. Keras started supporting it as a backend, and became the default starting from the release of Keras v1.1.0.
     - Keras started making TensorFlow default due to its popularity; and TensorFlow users were also becoming increasingly drawn to the simplicity of the high-level Keras API.
- Google announced TensorFlow 2.0 in June 2019, they declared that Keras is now the official high-level API of TensorFlow.

[Link](https://www.pyimagesearch.com/2019/10/21/keras-vs-tf-keras-whats-the-difference-in-tensorflow-2-0/)

In [3]:
import tensorflow as tf
import numpy as np
import keras

In [4]:
print(tf.__version__)

2.4.1


## Keras and tf.keras

- tf.keras submodule was introduced in TensorFlow v1.10.0, integrating Keras directly within TensorFlow package itself.
- Release of Keras 2.3.0: 
     - It is the first release of Keras that brings the Keras package in sync with tf.keras
     - It is the final release of Keras that will support multiple backends 
     - The keras package will only support bug fixes. Developers should start using tf.keras

In [5]:
tf.keras == keras

False

In [6]:
tf.keras.Sequential == keras.models.Sequential

True

In [7]:
tf.keras.models.Model == tf.keras.Model

True

# Eager Execution

https://towardsdatascience.com/eager-execution-vs-graph-execution-which-is-better-38162ea4dbf6


no session

no initialization

https://www.youtube.com/watch?v=Up9CvRLIIIw

@tf.function

a.assign
a.assign_add

Eager execution is a powerful execution environment that evaluates operations immediately. It does not build graphs, and the operations return actual values instead of computational graphs to run later. With Eager execution, TensorFlow calculates the values of tensors as they occur in your code.

In [9]:
# In Tensorflow 2.0, eager execution is enabled by default.
tf.executing_eagerly()

True

In [10]:
x = [[2.]]
m = tf.matmul(x,x)
print("hello, {}".format(m))     #Return results immediately 

hello, [[4.]]


In TensorFlow1.x, the above code will return:

      hello, Tensor("MatMul:0", shape=(1, 1), dtype=float32)

### Eager execution

<font color= red>Easy-to-build\&test</font>

Eager execution is easy to implement, and simplify the model building experience. Advantages of eager execution:

- **An intuitive interface** with natural Python code and data structures;
- **Easier debugging** with calling operations directly to inspect and test models;
- **Natural control flow** with Python, instead of graph control flow; and
- Support for **GPU & TPU acceleration**.

### Graph execution

<font color= red>Efficient and fast</font>

Eager execution is slower than graph execution since eager execution runs all operations one-by-one in Python, it cannot take advantage of potential acceleration opportunities.

Graphs are easy-to-optimize, simplify arithmetic operations. In graph execution, evaluation of all the operations happens only after we've called our program entirely. So, graph execution is
- **Very Fast**
- **Very Flexible**
- **Runs in parallel**, even in sub-operation level;
- **Very efficient**, on multiple devices
- with **GPU & TPU acceleration** capability

Graph execution is ideal for large model training. For small model training, beginners, eager execution is better suited.

### Why TensorFlow adopted Eager Execution?

- Before version 2.0, TensorFlow prioritized graph execution because it was fast, effiicent, and flexible. But it is difficult to implement.
- PyTorch adopted a different approach and prioritized dynamic computation graphs, which is a similar concept to eager execution. Although they are not that efficient, it is intuitive and easy to implement. Then PyTorch became attractive for the newcommers.
- TensorFlow felt threatened, so the TensorFlow team adopted eager execution as the default execution method, and graph execution is optional.

In TensorFlow 2.0, you can decorate a Python function using tf.function() to run it as a single graph object. With this new method, you can easily build models and gain all the graph execution benefits.

In [11]:
a = tf.constant([[1,2],[3,4]])
print(a)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [12]:
b = tf.add(a,1)
print(b)

tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32)


In [13]:
print(a*b)

tf.Tensor(
[[ 2  6]
 [12 20]], shape=(2, 2), dtype=int32)


In [14]:
c = np.multiply(a,b)
print(c)

[[ 2  6]
 [12 20]]


In [25]:
a.numpy()

array([[1, 2],
       [3, 4]], dtype=int32)

# Tensors

- variables
- constant
- Placeholder
- SparseTensor

In [26]:
## scalar
string = tf.Variable("this is a string", tf.string) 
number = tf.Variable(324, tf.int16)
floating = tf.Variable(3.567, tf.float64)

In [31]:
number

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=324>

In [ ]:
tf.Variable([[0.3,0.5],[1,0.2]],dtype=tf.float64)

In [ ]:
x = tf.Variable(2.0)

In [3]:
x = tf.constant([1., 2.])

In [8]:
x.numpy()

array([1., 2.], dtype=float32)

In [32]:
rank1_tensor = tf.Variable(["Test"], tf.string) 
rank2_tensor = tf.Variable([["test", "ok"], ["test", "yes"]], tf.string)

In [34]:
tf.rank(rank1_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [35]:
tf.rank(number)

<tf.Tensor: shape=(), dtype=int32, numpy=0>

In [37]:
rank2_tensor.shape

TensorShape([2, 2])

In [39]:
tensor1 = tf.ones([1, 2, 3])  #tf.zeros
print(tensor1)
# y.numpy()     #no numpy()
tensor2 = tf.reshape(tensor1,[2,3,1])
print(tensor2)
tensor3 = tf.reshape(tensor2,[3,-1])
print(tensor3)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)
tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


In [ ]:
tf.compat.v1.disable_eager_execution()
placeholder

# session

In [ ]:
# work/DNN/scratch

#work/DNN/ODE-tf/tf2 vs tf1 (eg from stack)

In [10]:
with tf.compat.v1.Session() as sess:
    x = tf.constant([1., 2.])
    y = x**2
    tf.compat.v1.global_variables_initializer().run()
    print(y.eval())

[1. 4.]


In [11]:
with tf.compat.v1.Session() as sess:
    init = tf.compat.v1.global_variables_initializer()
    sess.run(init)
    x = tf.constant([1., 2.])
    y = x**2
    print(y.eval())

[1. 4.]


In [18]:
tf.compat.v1.disable_eager_execution()
x = tf.compat.v1.placeholder(tf.float64,[None,1])
y = x**2

init = tf.compat.v1.global_variables_initializer()
with tf.compat.v1.Session() as sess:
    sess.run(init)
    a = np.array([[1],[2]])   #cannot be tf.constant
    c = sess.run(y,feed_dict={x:a})    #print(c) not print(y)
    print(c)

[[1.]
 [4.]]


# function

In [19]:
@tf.function
def example():
    a = tf.constant(0.)
    b = 2 * a **2
    return tf.gradients(a + b, [a, b], stop_gradients=[a, b])

example()

[<tf.Tensor 'PartitionedCall:0' shape=() dtype=float32>,
 <tf.Tensor 'PartitionedCall:1' shape=() dtype=float32>]

# operations

In [ ]:
tf.compat.v1.global_variables_initializer()

## gradient

In [ ]:
# tf.gradients

x = tf.Variable(2.0)
y = tf.Variable(3.0)

with tf.GradientTape() as t:
    x_sq = x * x
    with t.stop_recording():
        y_sq = y * y
    z = x_sq + y_sq

grad = tf.gradient(z, {'x': x, 'y': y})

print('dz/dx:', grad['x'])  # 2*x => 4
print('dz/dy:', grad['y'])

multiple tapes

In [ ]:
#work/python/keras-1

x0 = tf.constant(0.0)
x1 = tf.constant(0.0)

with tf.GradientTape() as tape0, tf.GradientTape() as tape1:
    tape0.watch(x0)
    tape1.watch(x1)

    y0 = tf.math.sin(x0)
    y1 = tf.nn.sigmoid(x1)

    y = y0 + y1

    ys = tf.reduce_sum(y)

In [ ]:
print(tape0.gradient(ys, x0).numpy())  # cos(x) => 1.0

print(tape1.gradient(ys, x1).numpy())   # sigmoid(x1)*(1-sigmoid(x1)) => 0.25

higher-order gradient

In [ ]:
#work/python/keras-1

x = tf.Variable(1.0)  # Create a Tensorflow variable initialized to 1.0

with tf.GradientTape() as t2:
    with tf.GradientTape() as t1:
        y = x * x * x

    # Compute the gradient inside the outer `t2` context manager
    # which means the gradient computation is differentiable as well.
    dy_dx = t1.gradient(y, x)
d2y_dx2 = t2.gradient(dy_dx, x)

print('dy_dx:', dy_dx.numpy())  # 3 * x**2 => 3.0
print('d2y_dx2:', d2y_dx2.numpy())  # 6 * x => 6.0

## reduce_sum

In [ ]:
#work/python/keras-1

# x has a shape of (2, 3) (two rows and three columns):
x = tf.constant([[1, 1, 1], [1, 1, 1]])
print(x.numpy())

# sum all the elements
# 1 + 1 + 1 + 1 + 1+ 1 = 6
print(tf.reduce_sum(x).numpy())

# reduce along the first dimension
# the result is [1, 1, 1] + [1, 1, 1] = [2, 2, 2]
print(tf.reduce_sum(x, 0).numpy())

# reduce along the second dimension
# the result is [1, 1] + [1, 1] + [1, 1] = [3, 3]
print(tf.reduce_sum(x, 1).numpy())

# keep the original dimensions
print(tf.reduce_sum(x, 1, keepdims=True).numpy())


# reduce along both dimensions
# the result is 1 + 1 + 1 + 1 + 1 + 1 = 6
# or, equivalently, reduce along rows, then reduce the resultant array
# [1, 1, 1] + [1, 1, 1] = [2, 2, 2]
# 2 + 2 + 2 = 6
print(tf.reduce_sum(x, [0, 1]).numpy())



In [ ]:
tf.compat.v1.squeeze

In [ ]:
tf.dynamic_stitch()

In [ ]:
tf.slice    #work/DNN/scratch

In [ ]:
tf.compat.v1.get_variable     #work/DNN/scratch

var2 = tf.compat.v1.get_variable(initializer=tf.constant_initializer(3.), dtype=tf.float64, name="var1", shape=[2,3])

In [ ]:
tf.math.square(2)    #work/DNN/scratch

def mysquare(x):
    return tf.math.square(x)

with tf.compat.v1.Session() as sess:
    xx = tf.constant([1., 2.])
    yy = mysquare(xx)
    tf.compat.v1.global_variables_initializer().run()

    print(xx.eval(), yy.eval())